"""Settle detector polarity against text whose authorship is known.

This is an opt-in diagnostic, not part of the test suite: it downloads and runs
the real models. It answers one question — does a high score actually mean
"machine written" for each detector, or is the polarity inverted?

Ground truth:
  human — prose shipped in packages released years before consumer LLMs.
  machine — text generated by a language model for this probe.

Run from the repository root:
    HF_HOME=.model-cache .venv/bin/python tools/polarity_probe.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "worker"))

from slop_detector.main import read_hf_token  # noqa: E402
from slop_detector.models import (  # noqa: E402
    TEXT_MODELS,
    TransformersLoader,
    select_runtime_device,
)

SITE_PACKAGES = Path(".venv/lib/python3.12/site-packages")

# Package prose predating consumer LLMs. defusedxml 0.7.1 shipped in 2021,
# sentencepiece's README dates to 2018, mpmath's and psutil's to the early 2010s.
HUMAN_SOURCES = [
    ("defusedxml", "defusedxml-0.7.1.dist-info/METADATA"),
    ("sentencepiece", "sentencepiece-0.2.2.dist-info/METADATA"),
    ("mpmath", "mpmath-1.3.0.dist-info/METADATA"),
    ("psutil", "psutil-7.2.2.dist-info/METADATA"),
]

# Written by a language model for this probe: machine-generated by construction.
MACHINE_SAMPLES = [
    (
        "llm-explainer",
        """Understanding how a distributed cache maintains consistency requires
        looking at three separate concerns. The first is invalidation: when a
        write lands on one node, the other nodes holding that key need to learn
        that their copy is stale. The second is ordering, because two writes
        arriving in different orders on different nodes will leave the cluster
        in divergent states. The third is failure handling, since a node that
        misses an invalidation message will happily serve stale data
        indefinitely. Most systems address these concerns with a combination of
        versioned entries, a total ordering mechanism such as a log, and a
        bounded staleness guarantee that limits how long a missed invalidation
        can go unnoticed. It is worth noting that these guarantees interact:
        strengthening one often weakens another, and the right balance depends
        heavily on the access patterns of the workload in question.""",
    ),
    (
        "llm-tutorial",
        """Setting up a reproducible Python environment involves a few important
        steps. First, create a virtual environment so that your project's
        dependencies remain isolated from the system interpreter. Next, pin your
        dependencies to exact versions in a requirements file, which ensures
        that every machine installing the project resolves to the same package
        versions. Finally, consider recording the hashes of those packages so
        that installation fails loudly if an artifact has been modified. Each of
        these steps addresses a different failure mode, and together they make
        it substantially easier to reason about what is actually running in
        production. Many teams also add a lock file and a scheduled job that
        checks for security advisories, which helps catch problems early rather
        than during an incident.""",
    ),
    (
        "llm-analysis",
        """The tradeoff between latency and throughput appears throughout systems
        design, and it is rarely possible to optimize both simultaneously.
        Batching requests improves throughput by amortizing fixed costs across
        more work, but it necessarily increases the latency of the earliest
        request in each batch, since that request must wait for the batch to
        fill. Conversely, processing each request immediately minimizes latency
        while sacrificing the efficiency gains that batching provides. In
        practice, systems often adopt an adaptive strategy: they batch
        aggressively when load is high and the queue is already deep, and
        process immediately when load is low and the marginal throughput gain
        would be small. This approach captures most of the benefit of both
        strategies without committing fully to either one.""",
    ),
]


def clean(raw: str) -> str:
    """Strip metadata headers, badges, and markup so only prose is scored."""
    body = raw.split("\n\n", 1)[-1]
    body = re.sub(r"!?\[[^\]]*\]\([^)]*\)", " ", body)      # markdown links/images
    body = re.sub(r"^\s*[|+:.-]{2,}.*$", " ", body, flags=re.M)  # tables, rules
    body = re.sub(r"^\s*(?:[-*=~^]{3,}|\.\. .*|\s{4,}\S.*)$", " ", body, flags=re.M)
    body = re.sub(r"[`*_#>]+", " ", body)
    body = re.sub(r"https?://\S+", " ", body)
    body = re.sub(r"[ \t]+", " ", body)
    prose = [line.strip() for line in body.splitlines() if len(line.strip()) > 40]
    return "\n".join(prose)[:4000]


def load_samples() -> list[tuple[str, str, str]]:
    samples = []
    for name, relative in HUMAN_SOURCES:
        path = SITE_PACKAGES / relative
        if not path.is_file():
            print(f"  (skipping {name}: {path} not installed)")
            continue
        text = clean(path.read_text(errors="replace"))
        if len(text) > 500:
            samples.append(("human", name, text))
    for name, text in MACHINE_SAMPLES:
        samples.append(("machine", name, " ".join(text.split())))
    return samples


def main() -> int:
    samples = load_samples()
    humans = [s for s in samples if s[0] == "human"]
    machines = [s for s in samples if s[0] == "machine"]
    print(f"{len(humans)} known-human and {len(machines)} known-machine samples\n")

    device, _ = select_runtime_device()
    loader = TransformersLoader(read_hf_token())
    verdicts = {}

    for model in TEXT_MODELS:
        predict = loader.load_text(model, device)
        print(f"{model.name} ({model.model_id})")
        means = {}
        for truth in ("human", "machine"):
            scores = [
                predict(text[: model.max_characters])["ai"]
                for label, _, text in samples
                if label == truth
            ]
            means[truth] = sum(scores) / len(scores)
            for (label, name, _), score in zip(
                [s for s in samples if s[0] == truth], scores
            ):
                print(f"  {truth:8} {name:16} score={score:.4f}")
        gap = means["machine"] - means["human"]
        verdicts[model.name] = gap
        print(
            f"  mean(human)={means['human']:.4f}  mean(machine)={means['machine']:.4f}"
            f"  gap={gap:+.4f}\n"
        )
        loader.release()

    print("=" * 60)
    for name, gap in verdicts.items():
        if gap > 0.2:
            print(f"{name}: polarity CORRECT (machine scores higher by {gap:+.3f})")
        elif gap < -0.2:
            print(f"{name}: polarity INVERTED (machine scores lower by {gap:+.3f})")
        else:
            print(f"{name}: INCONCLUSIVE (gap {gap:+.3f} — the model is not separating)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
